[2023-02-19T23:35:46.908+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: predictit_dag.is_api_available scheduled__2023-02-18T00:00:00+00:00 [queued]>
[2023-02-19T23:35:46.917+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: predictit_dag.is_api_available scheduled__2023-02-18T00:00:00+00:00 [queued]>
[2023-02-19T23:35:46.917+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-19T23:35:46.918+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-02-19T23:35:46.918+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-19T23:35:46.929+0000] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-02-18 00:00:00+00:00
[2023-02-19T23:35:46.933+0000] {standard_task_runner.py:55} INFO - Started process 23647 to run task
[2023-02-19T23:35:46.934+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'predictit_dag', 'is_api_available', 'scheduled__2023-02-18T00:00:00+00:00', '--job-id', '511', '--raw', '--subdir', 'DAGS_FOLDER/predictit_dag.py', '--cfg-path', '/tmp/tmp8gnj7tqt']
[2023-02-19T23:35:46.935+0000] {standard_task_runner.py:83} INFO - Job 511: Subtask is_api_available
[2023-02-19T23:35:46.977+0000] {task_command.py:388} INFO - Running <TaskInstance: predictit_dag.is_api_available scheduled__2023-02-18T00:00:00+00:00 [running]> on host 9e0dc30811b3
[2023-02-19T23:35:47.028+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=kyunlee@yahoo.com
AIRFLOW_CTX_DAG_OWNER=kyun
AIRFLOW_CTX_DAG_ID=predictit_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-02-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-18T00:00:00+00:00
[2023-02-19T23:35:47.029+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:35:47.036+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:35:47.376+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:35:47.376+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:36:47.438+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:36:47.445+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:36:47.623+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:36:47.623+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:37:47.654+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:37:47.661+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:37:47.978+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:37:47.978+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:38:47.994+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:38:48.001+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:38:48.317+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:38:48.317+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:39:48.332+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:39:48.339+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:39:48.654+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:39:48.655+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:40:48.714+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:40:48.721+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:40:49.068+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:40:49.068+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:41:49.124+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:41:49.131+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:41:49.448+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:41:49.448+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:42:49.504+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:42:49.511+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:42:49.854+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:42:49.854+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:43:49.916+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:43:49.923+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:43:50.270+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:43:50.270+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:44:50.331+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:44:50.337+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:44:50.686+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:44:50.686+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:45:50.745+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:45:50.752+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:45:50.943+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:45:50.944+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:46:51.005+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:46:51.011+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:46:51.322+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:46:51.323+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:47:51.344+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:47:51.350+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:47:51.692+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:47:51.693+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:48:51.754+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:48:51.761+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:48:52.079+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:48:52.080+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:49:52.122+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:49:52.128+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:49:52.430+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:49:52.430+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:50:52.477+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:50:52.483+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:50:52.810+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:50:52.811+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:51:52.864+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:51:52.870+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:51:53.216+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:51:53.216+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:52:53.274+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:52:53.282+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:52:53.596+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:52:53.596+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:53:53.647+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:53:53.654+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:53:53.970+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:53:53.970+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:54:54.032+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:54:54.038+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:54:54.363+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:54:54.363+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:55:54.424+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:55:54.430+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:55:55.215+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:55:55.215+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:56:55.277+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:56:55.284+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:56:55.600+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:56:55.600+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:57:55.662+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:57:55.718+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:57:55.890+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:57:55.891+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:58:55.932+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:58:55.938+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:58:56.249+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:58:56.249+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-19T23:59:56.291+0000] {http.py:122} INFO - Poking: api/
[2023-02-19T23:59:56.297+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-19T23:59:56.624+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-19T23:59:56.624+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:00:56.684+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:00:56.690+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:00:57.015+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:00:57.015+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:01:57.050+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:01:57.056+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:01:57.381+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:01:57.381+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:02:57.434+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:02:57.444+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:02:57.757+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:02:57.757+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:03:57.814+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:03:57.820+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:03:58.150+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:03:58.151+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:04:58.207+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:04:58.213+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:04:58.532+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:04:58.533+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:05:58.595+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:05:58.601+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:05:58.925+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:05:58.925+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:06:58.984+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:06:58.991+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:06:59.306+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:06:59.306+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:07:59.367+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:07:59.373+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:07:59.705+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:07:59.706+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:08:59.764+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:08:59.770+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:09:00.125+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:09:00.125+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:10:00.184+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:10:00.190+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:10:00.383+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:10:00.383+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:11:00.445+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:11:00.452+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:11:00.798+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:11:00.799+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:12:00.854+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:12:00.867+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:12:01.169+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:12:01.170+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:13:01.224+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:13:01.230+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:13:01.543+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:13:01.544+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:14:01.550+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:14:01.557+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:14:01.884+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:14:01.884+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:15:01.944+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:15:01.950+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:15:02.249+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:15:02.250+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:16:02.304+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:16:02.310+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:16:02.631+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:16:02.631+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:17:02.676+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:17:02.682+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:17:02.996+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:17:02.996+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:18:03.058+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:18:03.064+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:18:03.267+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:18:03.267+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:19:03.324+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:19:03.331+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:19:03.638+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:19:03.639+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:20:03.663+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:20:03.670+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:20:03.983+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:20:03.984+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:21:04.045+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:21:04.051+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:21:04.397+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:21:04.397+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:22:04.459+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:22:04.466+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:22:04.787+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:22:04.787+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:23:04.849+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:23:04.856+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:23:05.168+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:23:05.169+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:24:05.227+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:24:05.234+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:24:05.542+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:24:05.543+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:25:05.603+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:25:05.611+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:25:05.916+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:25:05.917+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:26:05.976+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:26:05.983+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:26:06.368+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:26:06.369+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:27:06.409+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:27:06.417+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:27:06.734+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:27:06.735+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:28:06.787+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:28:06.794+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:28:07.100+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:28:07.101+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:29:07.153+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:29:07.159+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:29:07.477+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:29:07.477+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:30:07.537+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:30:07.543+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:30:07.859+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:30:07.860+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:31:07.913+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:31:07.919+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:31:08.436+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:31:08.437+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:32:08.477+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:32:08.482+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:32:08.657+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:32:08.657+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:33:08.719+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:33:08.725+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:33:08.898+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:33:08.899+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:34:08.953+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:34:08.959+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:34:09.281+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:34:09.281+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:35:09.328+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:35:09.334+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:35:09.644+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:35:09.644+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:36:09.703+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:36:09.710+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:36:10.023+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:36:10.023+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:37:10.053+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:37:10.059+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:37:10.370+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:37:10.371+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:38:10.423+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:38:10.429+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:38:10.772+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:38:10.773+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:39:10.833+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:39:10.840+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:39:11.013+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:39:11.013+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:40:11.050+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:40:11.056+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:40:11.363+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:40:11.363+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:41:11.423+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:41:11.430+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:41:11.759+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:41:11.759+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:42:11.813+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:42:11.820+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:42:12.140+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:42:12.140+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:43:12.200+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:43:12.206+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:43:12.516+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:43:12.517+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:44:12.573+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:44:12.580+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:44:12.910+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:44:12.911+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:45:12.953+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:45:12.959+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:45:13.270+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:45:13.270+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:46:13.301+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:46:13.307+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:46:13.807+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:46:13.807+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:47:13.859+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:47:13.865+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:47:14.184+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:47:14.184+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:48:14.245+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:48:14.337+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:48:14.675+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:48:14.676+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:49:14.703+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:49:14.709+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:49:15.014+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:49:15.015+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:50:15.073+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:50:15.081+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:50:15.396+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:50:15.396+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:51:15.436+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:51:15.441+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:51:15.769+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:51:15.769+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:52:15.823+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:52:15.831+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:52:16.125+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:52:16.126+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:53:16.163+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:53:16.168+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:53:16.487+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:53:16.488+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:54:16.543+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:54:16.548+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:54:16.855+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:54:16.856+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:55:16.913+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:55:16.918+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:55:17.076+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:55:17.077+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:56:17.138+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:56:17.144+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:56:17.318+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:56:17.318+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:57:17.325+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:57:17.330+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:57:17.652+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:57:17.653+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:58:17.713+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:58:17.719+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:58:18.044+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:58:18.044+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:59:18.079+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:59:18.085+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:59:18.395+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:59:18.396+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:00:18.435+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:00:18.440+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:00:18.757+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:00:18.757+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:01:18.787+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:01:18.792+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:01:19.003+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:01:19.003+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:02:19.046+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:02:19.051+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:02:19.365+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:02:19.365+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:03:19.427+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:03:19.433+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:03:19.753+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:03:19.753+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:04:19.778+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:04:19.783+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:04:20.097+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:04:20.098+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:05:20.121+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:05:20.127+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:05:20.435+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:05:20.435+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:06:20.457+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:06:20.463+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:06:20.810+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:06:20.810+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:07:20.872+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:07:20.877+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:07:21.190+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:07:21.190+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:08:21.242+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:08:21.248+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:08:21.561+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:08:21.561+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:09:21.623+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:09:21.629+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:09:21.934+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:09:21.935+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:10:21.996+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:10:22.001+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:10:22.389+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:10:22.390+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:11:22.443+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:11:22.448+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:11:22.796+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:11:22.796+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
