[2023-02-20T00:00:01.035+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: predictit_dag.is_api_available scheduled__2023-02-19T00:00:00+00:00 [queued]>
[2023-02-20T00:00:01.049+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: predictit_dag.is_api_available scheduled__2023-02-19T00:00:00+00:00 [queued]>
[2023-02-20T00:00:01.050+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T00:00:01.050+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-02-20T00:00:01.051+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T00:00:01.071+0000] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-02-19 00:00:00+00:00
[2023-02-20T00:00:01.078+0000] {standard_task_runner.py:55} INFO - Started process 26670 to run task
[2023-02-20T00:00:01.083+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'predictit_dag', 'is_api_available', 'scheduled__2023-02-19T00:00:00+00:00', '--job-id', '520', '--raw', '--subdir', 'DAGS_FOLDER/predictit_dag.py', '--cfg-path', '/tmp/tmpc9up8ky9']
[2023-02-20T00:00:01.085+0000] {standard_task_runner.py:83} INFO - Job 520: Subtask is_api_available
[2023-02-20T00:00:01.156+0000] {task_command.py:388} INFO - Running <TaskInstance: predictit_dag.is_api_available scheduled__2023-02-19T00:00:00+00:00 [running]> on host 9e0dc30811b3
[2023-02-20T00:00:01.222+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=kyunlee@yahoo.com
AIRFLOW_CTX_DAG_OWNER=kyun
AIRFLOW_CTX_DAG_ID=predictit_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-02-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-19T00:00:00+00:00
[2023-02-20T00:00:01.223+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:00:01.229+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:00:01.549+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:00:01.550+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:01:01.604+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:01:01.609+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:01:01.964+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:01:01.964+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:02:01.999+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:02:02.006+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:02:02.321+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:02:02.321+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:03:02.374+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:03:02.380+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:03:02.733+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:03:02.734+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:04:02.794+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:04:02.801+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:04:03.163+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:04:03.164+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:05:03.177+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:05:03.184+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:05:03.513+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:05:03.513+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:06:03.533+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:06:03.540+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:06:03.850+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:06:03.851+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:07:03.910+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:07:03.917+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:07:04.231+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:07:04.231+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:08:04.292+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:08:04.299+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:08:04.626+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:08:04.626+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:09:04.635+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:09:04.642+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:09:04.955+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:09:04.956+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:10:05.017+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:10:05.024+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:10:05.335+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:10:05.336+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:11:05.384+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:11:05.391+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:11:05.724+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:11:05.724+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:12:05.783+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:12:05.790+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:12:05.962+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:12:05.962+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:13:06.024+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:13:06.030+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:13:06.343+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:13:06.343+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:14:06.398+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:14:06.405+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:14:06.693+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:14:06.694+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:15:06.746+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:15:06.753+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:15:07.056+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:15:07.056+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:16:07.116+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:16:07.122+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:16:07.429+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:16:07.430+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:17:07.453+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:17:07.459+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:17:07.626+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:17:07.627+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:18:07.657+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:18:07.663+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:18:07.972+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:18:07.973+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:19:08.015+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:19:08.021+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:19:08.322+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:19:08.323+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:20:08.381+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:20:08.388+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:20:08.673+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:20:08.673+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:21:08.735+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:21:08.758+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:21:09.072+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:21:09.072+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:22:09.079+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:22:09.085+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:22:09.406+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:22:09.406+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:23:09.468+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:23:09.474+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:23:09.769+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:23:09.769+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:24:09.828+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:24:09.834+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:24:10.142+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:24:10.142+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:25:10.183+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:25:10.189+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:25:10.478+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:25:10.478+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:26:10.537+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:26:10.544+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:26:10.724+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:26:10.725+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:27:10.773+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:27:10.780+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:27:10.952+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:27:10.953+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:28:10.990+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:28:10.996+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:28:11.289+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:28:11.289+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:29:11.295+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:29:11.301+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:29:11.595+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:29:11.595+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:30:11.657+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:30:11.663+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:30:11.813+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:30:11.814+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:31:11.873+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:31:11.879+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:31:12.030+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:31:12.030+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:32:12.091+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:32:12.097+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:32:12.399+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:32:12.400+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:33:12.455+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:33:12.461+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:33:12.754+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:33:12.754+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:34:12.816+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:34:12.823+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:34:13.104+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:34:13.104+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:35:13.163+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:35:13.170+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:35:13.330+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:35:13.331+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:36:13.383+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:36:13.390+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:36:13.543+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:36:13.543+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:37:13.588+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:37:13.596+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:37:13.891+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:37:13.892+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:38:13.948+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:38:13.954+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:38:14.107+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:38:14.107+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:39:14.135+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:39:14.141+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:39:14.295+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:39:14.296+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:40:14.354+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:40:14.361+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:40:14.659+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:40:14.660+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:41:14.721+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:41:14.729+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:41:15.025+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:41:15.026+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:42:15.083+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:42:15.090+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:42:15.384+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:42:15.384+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:43:15.443+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:43:15.450+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:43:15.734+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:43:15.735+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:44:15.794+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:44:15.801+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:44:16.104+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:44:16.105+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:45:16.143+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:45:16.149+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:45:16.302+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:45:16.303+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:46:16.337+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:46:16.344+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:46:16.652+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:46:16.653+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:47:16.694+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:47:16.699+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:47:16.981+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:47:16.981+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:48:17.029+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:48:17.036+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:48:17.324+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:48:17.324+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:49:17.385+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:49:17.391+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:49:17.673+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:49:17.673+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:50:17.717+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:50:17.722+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:50:18.010+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:50:18.011+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:51:18.051+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:51:18.056+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:51:18.344+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:51:18.344+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:52:18.401+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:52:18.407+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:52:18.703+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:52:18.703+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:53:18.723+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:53:18.729+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:53:19.010+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:53:19.010+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:54:19.063+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:54:19.093+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:54:19.393+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:54:19.394+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:55:19.455+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:55:19.462+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:55:19.755+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:55:19.755+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:56:19.787+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:56:19.793+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:56:20.081+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:56:20.081+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:57:20.139+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:57:20.145+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:57:20.446+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:57:20.446+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:58:20.503+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:58:20.509+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:58:20.800+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:58:20.800+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T00:59:20.818+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T00:59:20.824+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T00:59:21.111+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T00:59:21.111+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:00:21.163+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:00:21.227+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:00:21.530+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:00:21.530+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:01:21.549+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:01:21.555+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:01:21.849+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:01:21.850+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:02:21.903+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:02:21.909+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:02:22.198+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:02:22.199+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:03:22.213+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:03:22.218+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:03:22.521+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:03:22.521+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:04:22.583+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:04:22.588+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:04:22.748+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:04:22.748+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:05:22.761+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:05:22.767+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:05:22.920+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:05:22.920+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:06:22.982+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:06:22.988+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:06:23.288+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:06:23.288+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:07:23.343+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:07:23.349+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:07:23.509+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:07:23.509+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:08:23.570+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:08:23.577+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:08:23.881+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:08:23.882+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:09:23.945+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:09:23.952+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:09:24.127+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:09:24.127+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:10:24.189+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:10:24.195+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:10:24.546+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:10:24.546+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T01:11:24.569+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T01:11:24.575+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T01:11:24.861+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T01:11:24.861+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
