[2023-02-18T08:41:14.910+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: predictit_dag.is_api_available scheduled__2023-02-17T00:00:00+00:00 [queued]>
[2023-02-18T08:41:14.918+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: predictit_dag.is_api_available scheduled__2023-02-17T00:00:00+00:00 [queued]>
[2023-02-18T08:41:14.918+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-18T08:41:14.919+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-02-18T08:41:14.919+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-18T08:41:14.931+0000] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-02-17 00:00:00+00:00
[2023-02-18T08:41:14.936+0000] {standard_task_runner.py:55} INFO - Started process 19207 to run task
[2023-02-18T08:41:14.938+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'predictit_dag', 'is_api_available', 'scheduled__2023-02-17T00:00:00+00:00', '--job-id', '481', '--raw', '--subdir', 'DAGS_FOLDER/predictit_dag.py', '--cfg-path', '/tmp/tmpddiitg8i']
[2023-02-18T08:41:14.938+0000] {standard_task_runner.py:83} INFO - Job 481: Subtask is_api_available
[2023-02-18T08:41:14.980+0000] {task_command.py:388} INFO - Running <TaskInstance: predictit_dag.is_api_available scheduled__2023-02-17T00:00:00+00:00 [running]> on host 9e0dc30811b3
[2023-02-18T08:41:15.029+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=kyunlee@yahoo.com
AIRFLOW_CTX_DAG_OWNER=kyun
AIRFLOW_CTX_DAG_ID=predictit_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-02-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-17T00:00:00+00:00
[2023-02-18T08:41:15.030+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:41:15.036+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:41:15.659+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:41:15.659+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:42:15.721+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:42:15.727+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:42:16.277+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:42:16.278+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:43:16.337+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:43:16.344+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:43:16.786+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:43:16.787+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:44:16.847+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:44:16.853+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:44:17.029+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:44:17.030+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:45:17.077+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:45:17.083+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:45:17.398+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:45:17.398+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:46:17.457+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:46:17.463+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:46:17.649+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:46:17.649+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:47:17.707+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:47:17.714+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:47:18.023+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:47:18.023+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:48:18.056+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:48:18.062+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:48:18.411+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:48:18.412+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:49:18.467+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:49:18.473+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:49:18.791+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:49:18.792+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:50:18.847+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:50:18.853+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:50:19.067+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:50:19.067+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:51:19.072+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:51:19.078+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:51:19.451+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:51:19.452+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:52:19.507+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:52:19.513+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:52:19.863+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:52:19.864+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:53:19.925+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:53:19.931+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:53:20.246+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:53:20.246+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:54:20.307+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:54:20.313+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:54:20.628+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:54:20.629+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:55:20.688+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:55:20.694+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:55:20.857+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:55:20.858+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:56:20.920+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:56:20.926+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:56:21.256+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:56:21.257+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:57:21.319+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:57:21.324+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:57:21.635+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:57:21.635+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:58:21.686+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:58:21.692+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:58:21.995+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:58:21.995+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T08:59:22.057+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T08:59:22.064+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T08:59:22.370+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T08:59:22.370+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:00:22.427+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:00:22.432+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:00:22.745+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:00:22.746+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:01:22.807+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:01:22.814+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:01:23.173+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:01:23.173+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:02:23.227+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:02:23.234+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:02:23.535+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:02:23.535+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:03:23.551+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:03:23.557+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:03:23.725+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:03:23.725+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:04:23.787+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:04:23.794+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:04:23.964+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:04:23.964+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:05:24.022+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:05:24.027+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:05:24.328+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:05:24.329+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:06:24.387+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:06:24.393+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:06:24.705+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:06:24.706+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:07:24.730+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:07:24.735+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:07:24.906+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:07:24.906+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:08:24.968+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:08:24.975+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:08:25.272+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:08:25.273+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:09:25.327+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:09:25.333+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:09:25.640+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:09:25.641+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:10:25.697+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:10:25.703+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:10:26.028+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:10:26.029+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:11:26.047+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:11:26.053+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:11:26.377+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:11:26.377+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:12:26.423+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:12:26.429+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:12:26.732+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:12:26.732+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:13:26.787+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:13:26.793+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:13:27.142+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:13:27.142+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:14:27.203+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:14:27.209+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:14:27.500+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:14:27.501+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:15:27.548+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:15:27.557+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:15:27.862+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:15:27.862+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:16:27.910+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:16:27.918+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:16:28.502+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:16:28.502+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:17:28.516+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:17:28.525+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:17:28.882+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:17:28.882+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:18:28.937+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:18:28.945+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:18:29.270+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:18:29.271+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:19:29.332+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:19:29.342+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:19:29.653+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:19:29.653+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:20:29.707+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:20:29.716+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:20:30.026+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:20:30.026+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:21:30.087+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:21:30.096+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:21:30.454+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:21:30.454+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:22:30.513+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:22:30.522+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:22:30.850+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:22:30.850+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:23:30.907+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:23:30.915+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:23:31.212+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:23:31.212+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:24:31.267+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:24:31.277+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:24:31.599+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:24:31.600+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:25:31.627+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:25:31.636+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:25:31.966+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:25:31.967+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:26:31.983+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:26:31.992+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:26:32.314+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:26:32.315+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:27:32.376+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:27:32.386+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:27:32.708+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:27:32.709+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:28:32.714+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:28:32.723+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:28:33.023+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:28:33.023+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:29:33.077+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:29:33.086+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:29:33.385+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:29:33.385+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:30:33.438+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:30:33.446+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:30:33.760+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:30:33.760+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:31:33.798+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:31:33.806+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:31:34.147+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:31:34.147+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:32:34.192+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:32:34.200+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:32:34.518+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:32:34.519+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:33:34.547+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:33:34.554+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:33:34.862+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:33:34.862+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:34:34.908+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:34:34.916+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:34:35.217+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:34:35.217+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:35:35.258+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:35:35.266+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:35:35.572+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:35:35.572+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:36:35.634+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:36:35.641+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:36:35.970+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:36:35.970+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:37:36.027+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:37:36.032+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:37:36.373+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:37:36.374+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:38:36.417+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:38:36.425+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:38:37.059+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:38:37.059+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:39:37.121+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:39:37.127+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:39:37.430+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:39:37.431+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:40:37.481+0000] {http.py:122} INFO - Poking: api/
[2023-02-18T09:40:37.486+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-18T09:40:37.651+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-18T09:40:37.652+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-18T09:47:38.299+0000] {local_task_job.py:192} ERROR - Heartbeat time limit exceeded!
[2023-02-18T09:47:38.311+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 19207. PIDs of all processes in the group: [19207]
[2023-02-18T09:47:38.312+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 19207
[2023-02-18T09:47:38.313+0000] {taskinstance.py:1479} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-02-18T09:47:38.396+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 226, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1481, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-02-18T09:47:38.410+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=predictit_dag, task_id=is_api_available, execution_date=20230217T000000, start_date=20230218T084114, end_date=20230218T094738
[2023-02-18T09:47:38.490+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 481 for task is_api_available (Task received SIGTERM signal; 19207)
[2023-02-18T09:47:38.528+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=19207, status='terminated', exitcode=1, started='08:41:14') (19207) terminated with exit code 1
